// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef curveCombine_h
#define curveCombine_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "mytree.h"
#include <string>
#include "plotbox.h"
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Float_Input.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Native_File_Chooser.H>

class CurveCombineUI {
public:
  CurveCombineUI();
  Fl_Double_Window *mainWindow;
  Mytree *tree;
private:
  inline void cb_tree_i(Mytree*, void*);
  static void cb_tree(Mytree*, void*);
public:
  PlotBox *plotBox;
  Fl_Button *btnClear;
private:
  inline void cb_btnClear_i(Fl_Button*, void*);
  static void cb_btnClear(Fl_Button*, void*);
public:
  Fl_Float_Input *edtXLeft;
  Fl_Float_Input *edtYLeft;
  Fl_Float_Input *edtXCross;
  Fl_Float_Input *edtYCross;
  Fl_Float_Input *edtXRight;
  Fl_Float_Input *edtYRight;
  Fl_Button *btnExe;
private:
  inline void cb_btnExe_i(Fl_Button*, void*);
  static void cb_btnExe(Fl_Button*, void*);
public:
  Fl_Button *btnReset;
private:
  inline void cb_btnReset_i(Fl_Button*, void*);
  static void cb_btnReset(Fl_Button*, void*);
public:
  Fl_Float_Input *edtYLow;
private:
  inline void cb_edtYLow_i(Fl_Float_Input*, void*);
  static void cb_edtYLow(Fl_Float_Input*, void*);
public:
  Fl_Float_Input *edtYHigh;
private:
  inline void cb_edtYHigh_i(Fl_Float_Input*, void*);
  static void cb_edtYHigh(Fl_Float_Input*, void*);
public:
  Fl_Button *btnYLim;
  Fl_Value_Slider *sldX;
private:
  inline void cb_sldX_i(Fl_Value_Slider*, void*);
  static void cb_sldX(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *sldY;
private:
  inline void cb_sldY_i(Fl_Value_Slider*, void*);
  static void cb_sldY(Fl_Value_Slider*, void*);
public:
  Fl_Button *btnSave;
private:
  inline void cb_btnSave_i(Fl_Button*, void*);
  static void cb_btnSave(Fl_Button*, void*);
public:
  Fl_Box *bxXY;
  void show(int argc, char **argv);
};
#endif
